# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 188)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("calc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 341, 251))
        self.frame.setMinimumSize(QtCore.QSize(341, 251))
        self.frame.setMaximumSize(QtCore.QSize(341, 251))
        self.frame.setStyleSheet("background-color: rgb(213, 249, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt1 = QtWidgets.QLineEdit(self.frame)
        self.txt1.setGeometry(QtCore.QRect(50, 70, 101, 20))
        self.txt1.setObjectName("txt1")
        self.txt2 = QtWidgets.QLineEdit(self.frame)
        self.txt2.setGeometry(QtCore.QRect(170, 70, 101, 20))
        self.txt2.setText("")
        self.txt2.setObjectName("txt2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 47, 13))
        self.label_3.setObjectName("label_3")
        self.botao = QtWidgets.QPushButton(self.frame)
        self.botao.setGeometry(QtCore.QRect(60, 130, 101, 23))
        self.botao.setObjectName("botao")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(190, 130, 61, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(110, 100, 51, 21))
        self.label_4.setObjectName("label_4")
        self.txt_resultado = QtWidgets.QLineEdit(self.frame)
        self.txt_resultado.setGeometry(QtCore.QRect(170, 100, 101, 20))
        self.txt_resultado.setText("")
        self.txt_resultado.setReadOnly(True)
        self.txt_resultado.setObjectName("txt_resultado")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked['bool'].connect(self.txt2.clear)
        self.pushButton.clicked['bool'].connect(self.txt1.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora Python"))
        self.label.setText(_translate("MainWindow", "Numero 1"))
        self.label_3.setText(_translate("MainWindow", "Numero 2"))
        self.botao.setText(_translate("MainWindow", "Calcular"))
        self.pushButton.setText(_translate("MainWindow", "Limpar"))
        self.label_4.setText(_translate("MainWindow", "Resultado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
